/**
 * CRE SDK Abstraction Layer
 *
 * Provides a unified interface for CRE workflow execution.
 * When CRE_REGISTERED=true, uses the real @chainlink/cre-sdk trigger pattern.
 * Otherwise, runs in simulation mode using local handlers.
 *
 * Switchover instructions (Sean action required):
 *   1. Register at https://chain.link/hackathon (CAPTCHA TypeForm)
 *   2. Run: bun install -g @chainlink/cre-sdk
 *   3. Run: cre login && cre init
 *   4. Set CRE_REGISTERED=true in .env
 *   5. Set CRE_ETH_PRIVATE_KEY=<your-key> in .env
 *   6. Deploy workflows: cre workflow deploy ./workflows/price-alert
 *
 * Once CRE_REGISTERED=true, the handler below delegates to the real CRE SDK:
 *   cre.handler(http.trigger(), async (runtime, payload) => { ... })
 *
 * CRE SDK docs: https://docs.chain.link/cre
 * Package: @chainlink/cre-sdk (requires Bun >= 1.2.21)
 */

export interface CRERuntime {
  /** Fetch price data from Chainlink Data Streams */
  dataStreams: {
    getReport: (feedId: string) => Promise<{ price: number; timestamp: number; confidence: number }>;
  };
  /** HTTP client for external calls */
  http: {
    get: (url: string) => Promise<unknown>;
    post: (url: string, body: unknown) => Promise<unknown>;
  };
}

export interface CREHandlerOptions {
  /** CRE workflow name (used for routing in production) */
  workflowName: string;
  /** Simulation handler — used when CRE_REGISTERED is false */
  simulationHandler: (payload: Record<string, unknown>) => Promise<unknown>;
}

/**
 * Whether real CRE SDK is available (Sean has registered + deployed)
 */
export const CRE_REGISTERED = process.env.CRE_REGISTERED === "true";

/**
 * Create a CRE workflow handler.
 *
 * Usage:
 *   const handler = createCREHandler({
 *     workflowName: "price-feed",
 *     simulationHandler: async (payload) => { ... },  // always required
 *   });
 *
 *   // In simulation mode: runs simulationHandler directly
 *   // In production mode (CRE_REGISTERED=true): uses cre.handler(http.trigger(), ...)
 *
 * When switching to production:
 *   1. Set CRE_REGISTERED=true in environment
 *   2. The handler will log a warning that you need to use the CRE CLI deploy
 *   3. Real CRE workflows are WASM-compiled and run on the CRE network
 *   4. They are NOT called via this function in production — they are invoked
 *      by the CRE gateway directly when a payment is received
 */
export function createCREHandler(options: CREHandlerOptions): (payload: Record<string, unknown>) => Promise<unknown> {
  if (CRE_REGISTERED) {
    // Production mode: CRE SDK workflows run on the CRE network (not locally).
    // This code path should not normally be reached — production CRE workflows
    // are invoked by the CRE gateway, not by this handler.
    // Log a warning and fall back to simulation for local testing.
    console.warn(
      `[CRE] CRE_REGISTERED=true but workflow "${options.workflowName}" is running locally. ` +
      `In production, deploy via: cre workflow deploy ./workflows/${options.workflowName}`
    );
    return options.simulationHandler;
  }

  // Simulation mode: run handler locally
  return options.simulationHandler;
}

/**
 * Generate the real CRE SDK code pattern for a workflow.
 * Call this to get the code snippet to put in workflows/<name>/main.ts.
 *
 * This is what you'd write after CRE registration and deployment.
 */
export function getCREWorkflowTemplate(workflowName: string, handlerBody: string): string {
  return `
// workflows/${workflowName}/main.ts
// Generated by OpSpawn CRE abstraction layer
// Deploy with: cre workflow deploy ./workflows/${workflowName}

import { cre, http } from "@chainlink/cre-sdk"

const trigger = http.trigger({
  // x402 payment is automatically gated by CRE when deployed
  // No manual payment verification needed — CRE + x402 handles it
})

cre.handler(trigger, async (runtime, payload) => {
  ${handlerBody}
})
`.trim();
}

/**
 * CRE integration status for health checks and diagnostics.
 */
export function getCREStatus(): {
  registered: boolean;
  mode: "simulation" | "production";
  switchoverInstructions: string[];
} {
  return {
    registered: CRE_REGISTERED,
    mode: CRE_REGISTERED ? "production" : "simulation",
    switchoverInstructions: CRE_REGISTERED
      ? ["CRE SDK is active. Workflows run on the CRE network."]
      : [
          "1. Sean: register at https://chain.link/hackathon (CAPTCHA TypeForm)",
          "2. Run: bun install -g @chainlink/cre-sdk",
          "3. Run: cre login && cre init",
          "4. Set CRE_REGISTERED=true in .env",
          "5. Set CRE_ETH_PRIVATE_KEY=<your-key> in .env",
          "6. Deploy: cre workflow deploy ./workflows/price-alert",
        ],
  };
}
